books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('books/', views.book_view, name='books'),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('', include('tv_shows.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tv_shows/urls.py
from django.urls import path
from . import views

app_name = 'shows'

urlpatterns = [
    path('', views.ShowlistView.as_view(), name='show_list'),
    path('show_list/<int:id>/', views.ShowDetailView.as_view(), name='show_detail'),
    path('show_list_id/<int:id>/', views.show_id_key, name='show_id_key'),
    path('create_show/', views.ShowCreateView.as_view(), name='create_show'),
    path('show_list_delete/', views.show_list_delete_view, name='show_list_delete'),
    path('show_drop/<int:id>/delete/', views.ShowDropView.as_view(), name='show_drop'),
    path('show_list_update/', views.show_list_edit_view, name='show_list_update'),
    path('show_update/<int:id>/update/', views.ShowUpdateView.as_view(), name='show_update'),
    path('search/', views.SearchView.as_view(), name='search'),
]

books/models.py
from django.db import models


# Create your models here.
class Book(models.Model):
    book_name = models.CharField(max_length=100)
    book_description = models.TextField()
    book_image = models.ImageField(upload_to='')
    book_price = models.FloatField()
    book_author = models.CharField(max_length=100)
    book_created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.book_name

tv_shows/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

class Show(models.Model):
    TYPE_SHOW = (
        ('Спортивная', 'Спортивная'),
        ('Комедиеное', 'Комедиеное'),
        ('Семейное', 'Семейное'),
        ('Детское', 'Детское')
    )
    title = models.CharField(max_length=100, verbose_name='укажите название шоу')
    description = models.TextField(verbose_name='Дайте описание шоу', blank=True)
    image = models.ImageField(upload_to='shows/', verbose_name='добавте фото шоу')
    price = models.PositiveIntegerField(verbose_name='укажите цену',
                                       validators=[MinValueValidator(100),
                                                   MaxValueValidator(3000)])

    genre = models.CharField(max_length=100, choices=TYPE_SHOW)
    author = models.CharField(max_length=100, verbose_name='укажите автора')
    trailer = models.URLField(verbose_name='укажите ссылку на трейлер', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

tv_shows/forms.py
from django import forms
from . import models

class ShowForm(forms.ModelForm):
    class Meta:
      model = models.Show
      fields = "__all__"

books/views.py
from django.shortcuts import render
from . import models
# Create your views here.

def book_view(request):
    if request.method == 'GET':
        book = models.Book.objects.all()
        return render(request, template_name='books.html',
                      context={'book': book})

tv_shows/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . import models, forms
from django.urls import reverse
from django.http import HttpResponse
from django.views import generic


class ShowlistView(generic.ListView):
    template_name = 'shows/show_list.html'
    model = models.Show

    def get_queryset(self):
        return self.model.objects.all()


class ShowDetailView(generic.DetailView):
    template_name = 'shows/show_detail.html'
    context_object_name = 'show_id'

    def get_object(self, **kwargs):
        show_id = self.kwargs.get('id')
        return get_object_or_404(models.Show, id=show_id)


class ShowCreateView(generic.CreateView):
    template_name = 'crud/create_show.html'
    model = models.Show
    form_class = forms.ShowForm
    success_url = '/'

    def form_valid(self, form):
        print(form.cleaned_data)
        return super(ShowCreateView, self).form_valid(form=form)


def show_list_delete_view(request):
    if request.method == 'GET':
        show_delete = models.Show.objects.all()
        return render(request, template_name='crud/delete/show_list_delete.html',
                      context={'show_delete': show_delete})

def show_id_key(request, id):
    if request.method == "GET":
        show_id_ml = get_object_or_404(models.Show, id=id)
        return render(request, template_name='shows/show_id_key.html',
                      context={'show_id_ml': show_id_ml})


class ShowDropView(generic.DeleteView):
    template_name = 'crud/delete/confirm_delete.html'
    success_url = '/show_list_delete/'

    def get_object(self, **kwargs):
        show_id = self.kwargs.get('id')
        return get_object_or_404(models.Show, id=show_id)


def show_list_edit_view(request):
    if request.method == 'GET':
        show_update = models.Show.objects.all()
        return render(request, template_name='crud/update/show_list_update.html',
                      context={'show_update': show_update})

class ShowUpdateView(generic.UpdateView):
    template_name = 'crud/update/show_update.html'
    form_class = forms.ShowForm
    success_url = '/show_list_update/'

    def get_object(self, **kwargs):
        show_id = self.kwargs.get('id')
        return get_object_or_404(models.Show, id=show_id)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super(ShowUpdateView, self).form_valid(form=form)

class SearchView(generic.ListView):
    template_name = 'shows/show_list.html'
    paginate_by = 5

    def get_queryset(self):
        return models.Show.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q')
        return context






































# from django.shortcuts import render, get_object_or_404, redirect
# from . import models, forms
# from django.urls import reverse
# from django.http import HttpResponse
#
#
# def show_list(request):
#     if request.method == 'GET':
#         shows = models.Show.objects.all()
#         return render(request, template_name='shows/show_list.html',
#                       context={'shows': shows})
#
#
# def show_detail(request, id):
#     if request.method == "GET":
#         show_id = get_object_or_404(models.Show, id=id)
#         return render(request, template_name='shows/show_detail.html',
#                       context={'show_id': show_id})
#
#

#
# def show_create_view(request):
#     if request.method == "POST":
#         form = forms.ShowForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect(reverse('show_list'))
#     else:
#         form = forms.ShowForm()
#         return render(request, template_name='crud/create_show.html',
#                       context={"form": form})
#
#
# def show_list_delete_view(request):
#     if request.method == 'GET':
#         show_delete = models.Show.objects.all()
#         return render(request, template_name='crud/delete/show_list_delete.html',
#                       context={'show_delete': show_delete})
#
# def show_drop_view(request, id):
#     show_id = get_object_or_404(models.Show, id=id)
#     show_id.delete()
#     return redirect(reverse('show_list_delete'))
#
# # ________________________
#
# def show_list_edit_view(request):
#     if request.method == 'GET':
#         show_update = models.Show.objects.all()
#         return render(request, template_name='crud/update/show_list_update.html',
#                       context={'show_update': show_update})
#
#
#
#
# def show_update(request, id):
#     show_id = get_object_or_404(models.Show, id=id)
#
#     if request.method == 'POST':
#         form = forms.ShowForm(instance=show_id, data=request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect(reverse('show_list_update'))
#     else:
#         form = forms.ShowForm(instance=show_id)
#
#     return render(request, template_name='crud/update/show_update.html', context={
#         "form": form,
#         "show_id": show_id
#     })

templates/books.html
{% include 'shows/header.html' %}

<h1>Все книги</h1>
<ul>
    {% for i in book %}
    <li>
        <h2>{{i.book_name}}</h2>
        <p>{{i.book_description}}</p>
        <img src="{{i.book_image.url}}" alt="">
        <p>{{i.book_price}}</p>
        <p>{{i.book_author}}</p>
        <p>{{i.book_created_at}}</p>
    </li>
    {% endfor %}
</ul>
{% include 'shows/footer.html' %}

templates/crud/create_show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Добавить Шоу</h1>
<form action="/create_show/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Добавить</button>
</form>

</body>
</html>

templates/crud/delete/confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Вы уверены что хотите удалить этот объект?</h1>
<form method="POST", enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit">Да</button>
</form>
    <a href="/">Нет</a>
</body>
</html>

templates/crud/delete/show_list_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Выберите обект для удаления</h1>
<ul>
    {% for i in show_delete %}
    <li>
        <h2>{{i.title}}</h2>
        <button><a href="/show_drop/{{i.id}}/delete/">Удалить</a></button>
    </li>
    {% endfor %}
</ul>
</body>
</html>

templates/crud/update/show_list_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Выберите обект для изменения</h1>
<ul>
    {% for i in show_update %}
    <li>
        <h2>{{i.title}}</h2>
        <button><a href="/show_update/{{i.id}}/update/">Изменить</a></button>
    </li>
    {% endfor %}
</ul>
</body>
</html>

templates/crud/update/show_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Выберите что изменить</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Изменить</button>
</form>
</body>
</html>

templates/shows/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="#">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

templates/shows/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><nav class="navbar bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand" href="#">
      <img src="https://sun9-3.userapi.com/s/v1/ig2/WdBce9pELfrgUqK-NEtihWCoDqXqsHPvGyyVDcekHajcHz91QTTfyXL3g154nEr8Vd-MSIVRoL03Yfsy9bHp8NtU.jpg?size=200x200&quality=96&crop=29,29,841,841&ava=1" alt="Bootstrap" width="60" height="60">
    </a>
  </div>
</nav></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/books/">Книги</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Настройки
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/create_show/">Дабавить</a></li>
            <li><a class="dropdown-item" href="/show_list_update/">Изменить</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/show_list_delete/">Удалить</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin/">Перейти в админ</a>
        </li>
      </ul>
      <form action="{% url 'shows:search' %}" method="GET" class="d-flex" role="search">
        <input class="form-control me-2" type="text" name="q" type="search" placeholder="Поиск" aria-label="Поиск">
        <button class="btn btn-outline-success" type="submit">Поиск</button>
      </form>
    </div>
  </div>
</nav>

templates/shows/show_detail.html
{% include 'shows/header.html' %}
<h1>Подробнее об {{show_id.title}}</h1>
<p>{{show_id.description}}</p>
<img src="{{show_id.image.url}}" alt="">
<p>{{show_id.genre}}</p>
<p>{{show_id.author}}</p>
<p>{{show_id.price}}</p>
<a href="{{show_id.trailer}}">перейти по ссылке</a>
<p>{{show_id.created_ad}}</p>
{% include 'shows/footer.html' %}

templates/shows/show_id_key.html
{% include 'shows/header.html' %}
<h1>id фильма:</h1>
<p>ID=1887387781738</p>
{% include 'shows/footer.html' %}

templates/shows/show_list.html
{% include 'shows/header.html' %}
<div class="container">
    <h1>Список шоу</h1>
    <div class="row">
    {% for i in object_list %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <img src="{{ i.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ i.title }}</h5>
                    <p class="card-text">Price - {{ i.price }}</p>
                    <a href="/show_list/{{ i.id }}/" class="btn btn-primary">Детальная информация</a>
                    <a href="/show_list_id/{{ i.id }}/" class="btn btn-primary">получить id фильма</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% include 'shows/footer.html' %}